-- MySQL Script generated by MySQL Workbench
-- 10/12/17 15:07:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`addr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`addr` (
  `addr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for an address entry.',
  `addr_prefix` INT UNSIGNED NULL COMMENT 'Foreign Key.  Defines a formal title name prefix.  References \'common_prefix_id\' from table \'common_prefix\'. (RF)',
  `addr_fname` VARCHAR(30) NULL COMMENT 'Defines the first name of the entry. (RF)',
  `addr_lname` VARCHAR(30) NULL COMMENT 'Defines the last name of the entry. (RF)',
  `addr_mname` VARCHAR(30) NULL COMMENT 'Defines the middle name of the entry (Optional field)',
  `addr_nname` VARCHAR(30) NULL COMMENT 'Defines a nickname or alternate common name for the entry.',
  `addr_suffix` INT UNSIGNED NULL COMMENT 'Foreign Key.  Defines a common naming suffix.  References \'common_suffix_id\' from the table \'common_suffix\'',
  `addr_title` VARCHAR(100) NULL COMMENT 'Defines the official job title of the subject.',
  `addr_org` VARCHAR(100) NULL COMMENT 'Defines the organization the subject belongs to.',
  `addr_address_1` VARCHAR(255) NULL COMMENT 'Defines the primary address of the entry.',
  `addr_address_2` VARCHAR(255) NULL COMMENT 'Defines any additional address information of the entry',
  `addr_city` VARCHAR(255) NULL COMMENT 'Defines the city of the entry',
  `addr_state` INT UNSIGNED NULL COMMENT 'Defines the state of an entry',
  `addr_postcode` VARCHAR(10) NULL COMMENT 'Defines the post code of an entry',
  `addr_country` INT UNSIGNED NULL COMMENT 'Foreign Key.  Defines the country of the entry.  Referenced \'common_countries_id\' from table \'common_countries\'.',
  `addr_lat` FLOAT(10,6) NULL,
  `addr_lng` FLOAT(10,6) NULL,
  `addr_org_phone` VARCHAR(20) NULL COMMENT 'Defines the main phone number of entry.',
  `addr_org_phone_ext` VARCHAR(20) NULL COMMENT 'Defines main phone number extension for entry.',
  `addr_org_fax` VARCHAR(20) NULL COMMENT 'Define fax number for entry',
  `addr_direct` VARCHAR(20) NULL COMMENT 'Defines a direct dial number for entry.',
  `addr_mobile` VARCHAR(20) NULL COMMENT 'Defines a mobile phone number for entry.',
  `addr_email` VARCHAR(255) NULL COMMENT 'Defines an email address for entry.',
  `addr_url` VARCHAR(255) NULL COMMENT 'Defines a website for the entry.',
  `addr_admin_newsletter` TINYINT(1) NULL COMMENT 'A flagging field to determin if the entry should recieve a newsletter.',
  `addr_admin_calendars` TINYINT(1) NULL COMMENT 'A flagging field that will determine if a entry should recieve a end of year calendar mailing.',
  `addr_admin_gifts` TINYINT(1) NULL COMMENT 'A flagging field to define if the entry should recieve an end of year gift mailing',
  `addr_type_vendor` TINYINT(1) NULL COMMENT 'A flagging field to determin if the entry is a vendor.',
  `addr_type_client` TINYINT(1) NULL COMMENT 'A flagging field to determine if the entry is a client.',
  `addr_type_consultant` TINYINT(1) NULL COMMENT 'A flagging field to determine if an entry is a consultant',
  `addr_date_created` DATETIME NULL COMMENT 'Historical reference as to when the entry was created.',
  `addr_date_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change was made to the entry.',
  PRIMARY KEY (`addr_id`),
  INDEX `fk_addr-states_idx` (`addr_state` ASC),
  INDEX `fk_addr-countries_idx` (`addr_country` ASC),
  INDEX `fk_addr-suffix_idx` (`addr_suffix` ASC),
  INDEX `fk_addr-prefix_idx` (`addr_prefix` ASC),
  CONSTRAINT `fk_addr-states`
    FOREIGN KEY (`addr_state`)
    REFERENCES `OPSDev`.`common_usstates` (`common_usstates_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_addr-countries`
    FOREIGN KEY (`addr_country`)
    REFERENCES `OPSDev`.`common_countries` (`common_countries_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_addr-suffix`
    FOREIGN KEY (`addr_suffix`)
    REFERENCES `OPSDev`.`common_suffix` (`common_suffix_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_addr-prefix`
    FOREIGN KEY (`addr_prefix`)
    REFERENCES `OPSDev`.`common_prefix` (`common_prefix_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'addr - Contains address book entries.  All related tables have \'addr\' prefix.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
