-- MySQL Script generated by MySQL Workbench
-- 09/29/17 11:47:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`common_usstates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`common_usstates` (
  `common_usstates_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `common_usstates_abbr` VARCHAR(2) NULL,
  `common_usstates_full` VARCHAR(45) NULL,
  PRIMARY KEY (`common_usstates_id`))
ENGINE = InnoDB
COMMENT = 'common_usstates - A lookup table containing the two letter abbreviation and complete spelling of US states.';


-- -----------------------------------------------------
-- Table `OPSDev`.`common_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`common_countries` (
  `common_countries_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `common_countries_abbr` VARCHAR(2) NULL,
  `common_countries_full` VARCHAR(80) NULL,
  `common_countries_proper` VARCHAR(80) NULL,
  `common_countries_iso3` CHAR(3) NULL,
  `common_countries_numcode` SMALLINT(6) NULL,
  `common_countries_phonecode` INT(5) NULL,
  PRIMARY KEY (`common_countries_id`))
ENGINE = InnoDB
COMMENT = 'common_countries - A lookup table holding two letter abbreviations and full spelings of countries throughout the world.';


-- -----------------------------------------------------
-- Table `OPSDev`.`common_prefix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`common_prefix` (
  `common_prefix_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `common_prefix_abbr` VARCHAR(45) NULL,
  `common_prefix_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`common_prefix_id`))
ENGINE = InnoDB
COMMENT = 'common_prefix - A lookup table of the most common name prefixes.';


-- -----------------------------------------------------
-- Table `OPSDev`.`common_suffix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`common_suffix` (
  `common_suffix_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `common_suffix_abbr` VARCHAR(45) NULL,
  `common_suffix_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`common_suffix_id`))
ENGINE = InnoDB
COMMENT = 'common_prefix - A lookup table of the most common name suffixes.';


-- -----------------------------------------------------
-- Table `OPSDev`.`employee_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`employee_status` (
  `employee_status_id` INT NOT NULL AUTO_INCREMENT,
  `employee_status_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`employee_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OPSDev`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`employee` (
  `employee_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_fname` VARCHAR(30) NULL,
  `employee_lname` VARCHAR(30) NULL,
  `employee_mname` VARCHAR(30) NULL,
  `employee_prefix` INT UNSIGNED NULL,
  `employee_suffix` INT UNSIGNED NULL,
  `employee_dob` DATE NULL,
  `employee_addr_1` VARCHAR(45) NULL,
  `employee_addr_2` VARCHAR(45) NULL,
  `employee_city` VARCHAR(45) NULL,
  `employee_state` INT UNSIGNED NULL,
  `employee_postcode` VARCHAR(6) NULL,
  `employee_country` INT UNSIGNED NULL,
  `employee_home_phone` VARCHAR(20) NULL,
  `employee_mobile_phone` VARCHAR(20) NULL,
  `employee_hiredate` DATE NULL,
  `employee_acl` VARCHAR(45) NULL,
  `employee_status` INT NULL,
  `employee_subscription` INT NULL,
  `employee_username` VARCHAR(50) NULL,
  `employee_password` VARCHAR(60) NULL,
  `employee_created` DATETIME NULL,
  `employee_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_common_usstates_state_idx` (`employee_state` ASC),
  INDEX `fk_common_countries_country_idx` (`employee_country` ASC),
  INDEX `fk_employee-prefix_idx` (`employee_prefix` ASC),
  INDEX `fk_employee-suffix_idx` (`employee_suffix` ASC),
  INDEX `fk_employee-status_idx` (`employee_status` ASC),
  CONSTRAINT `fk_employee-state`
    FOREIGN KEY (`employee_state`)
    REFERENCES `OPSDev`.`common_usstates` (`common_usstates_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee-country`
    FOREIGN KEY (`employee_country`)
    REFERENCES `OPSDev`.`common_countries` (`common_countries_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee-prefix`
    FOREIGN KEY (`employee_prefix`)
    REFERENCES `OPSDev`.`common_prefix` (`common_prefix_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee-suffix`
    FOREIGN KEY (`employee_suffix`)
    REFERENCES `OPSDev`.`common_suffix` (`common_suffix_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee-status`
    FOREIGN KEY (`employee_status`)
    REFERENCES `OPSDev`.`employee_status` (`employee_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'employee - A table containing all the information related to an employee.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
