-- MySQL Script generated by MySQL Workbench
-- 10/05/17 13:31:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`security_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`security_sessions` (
  `security_sessions_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT UNSIGNED NOT NULL,
  `security_sessions_key` VARCHAR(60) NOT NULL,
  `security_sessions_adddress` VARCHAR(100) NOT NULL,
  `security_sessions_useragent` VARCHAR(200) NOT NULL,
  `security_sessions_expires` DATETIME NOT NULL,
  PRIMARY KEY (`security_sessions_id`),
  INDEX `fk-security-employee-id_idx` (`employee_id` ASC),
  CONSTRAINT `fk-security-employee-id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `OPSDev`.`employee` (`employee_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
