-- MySQL Script generated by MySQL Workbench
-- 02/06/18 10:31:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`addr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`addr` (
  `addr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for an address entry.',
  `addr_prefix` INT UNSIGNED NULL COMMENT 'Foreign Key.  Defines a formal title name prefix.  References \'common_prefix_id\' from table \'common_prefix\'. (RF)',
  `addr_fname` VARCHAR(30) NULL COMMENT 'Defines the first name of the entry. (RF)',
  `addr_lname` VARCHAR(30) NULL COMMENT 'Defines the last name of the entry. (RF)',
  `addr_mname` VARCHAR(30) NULL COMMENT 'Defines the middle name of the entry (Optional field)',
  `addr_nname` VARCHAR(30) NULL COMMENT 'Defines a nickname or alternate common name for the entry.',
  `addr_suffix` INT UNSIGNED NULL COMMENT 'Foreign Key.  Defines a common naming suffix.  References \'common_suffix_id\' from the table \'common_suffix\'',
  `addr_title` VARCHAR(100) NULL COMMENT 'Defines the official job title of the subject.',
  `addr_org_id` INT UNSIGNED NULL,
  `addr_address_1` VARCHAR(255) NULL COMMENT 'Defines the primary address of the entry.',
  `addr_address_2` VARCHAR(255) NULL COMMENT 'Defines any additional address information of the entry',
  `addr_city` VARCHAR(255) NULL COMMENT 'Defines the city of the entry',
  `addr_state` INT UNSIGNED NULL COMMENT 'Defines the state of an entry',
  `addr_postcode` VARCHAR(10) NULL COMMENT 'Defines the post code of an entry',
  `addr_country` INT UNSIGNED NULL COMMENT 'Foreign Key.  Defines the country of the entry.  Referenced \'common_countries_id\' from table \'common_countries\'.',
  `addr_lat` FLOAT(10,6) NULL,
  `addr_lng` FLOAT(10,6) NULL,
  `addr_org_phone` VARCHAR(20) NULL COMMENT 'Defines the main phone number of entry.',
  `addr_org_phone_ext` VARCHAR(20) NULL COMMENT 'Defines main phone number extension for entry.',
  `addr_org_fax` VARCHAR(20) NULL COMMENT 'Define fax number for entry',
  `addr_direct` VARCHAR(20) NULL COMMENT 'Defines a direct dial number for entry.',
  `addr_mobile` VARCHAR(20) NULL COMMENT 'Defines a mobile phone number for entry.',
  `addr_email` VARCHAR(255) NULL COMMENT 'Defines an email address for entry.',
  `addr_url` VARCHAR(255) NULL COMMENT 'Defines a website for the entry.',
  `addr_admin_newsletter` TINYINT(1) NULL COMMENT 'A flagging field to determin if the entry should recieve a newsletter.',
  `addr_admin_calendars` TINYINT(1) NULL COMMENT 'A flagging field that will determine if a entry should recieve a end of year calendar mailing.',
  `addr_admin_gifts` TINYINT(1) NULL COMMENT 'A flagging field to define if the entry should recieve an end of year gift mailing',
  `addr_type_vendor` TINYINT(1) NULL COMMENT 'A flagging field to determin if the entry is a vendor.',
  `addr_type_client` TINYINT(1) NULL COMMENT 'A flagging field to determine if the entry is a client.',
  `addr_type_consultant` TINYINT(1) NULL COMMENT 'A flagging field to determine if an entry is a consultant',
  `addr_date_created` DATETIME NULL COMMENT 'Historical reference as to when the entry was created.',
  `addr_date_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change was made to the entry.',
  PRIMARY KEY (`addr_id`),
  INDEX `fk_addr-states_idx` (`addr_state` ASC),
  INDEX `fk_addr-countries_idx` (`addr_country` ASC),
  INDEX `fk_addr-suffix_idx` (`addr_suffix` ASC),
  INDEX `fk_addr-prefix_idx` (`addr_prefix` ASC),
  INDEX `fk_addr-orgs_idx` (`addr_org_id` ASC),
  CONSTRAINT `fk_addr-states`
    FOREIGN KEY (`addr_state`)
    REFERENCES `OPSDev`.`common_usstates` (`common_usstates_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_addr-countries`
    FOREIGN KEY (`addr_country`)
    REFERENCES `OPSDev`.`common_countries` (`common_countries_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_addr-suffix`
    FOREIGN KEY (`addr_suffix`)
    REFERENCES `OPSDev`.`common_suffix` (`common_suffix_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_addr-prefix`
    FOREIGN KEY (`addr_prefix`)
    REFERENCES `OPSDev`.`common_prefix` (`common_prefix_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_addr-orgs`
    FOREIGN KEY (`addr_org_id`)
    REFERENCES `OPSDev`.`addr_orgs` (`addr_orgs_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'addr - Contains address book entries.  All related tables have \'addr\' prefix.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work` (
  `work_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  A unique identifier for work entries.',
  `work_year` YEAR NULL COMMENT 'Defines the archive year of the project in YEAR only format',
  `work_number` VARCHAR(10) NOT NULL COMMENT 'Defines the job number suffix.  Format is YY-XXX',
  `work_title` TEXT NOT NULL COMMENT 'Defines the title of the job.',
  `work_client` INT UNSIGNED NOT NULL COMMENT 'Foreign key to the ADDR_ORGS table.',
  `work_client_rep` INT UNSIGNED NOT NULL COMMENT 'The name from the ADDR entry',
  `work_db` TINYINT(1) NULL COMMENT 'Defines if a project is a Design/Build project',
  `work_status` INT(1) UNSIGNED NOT NULL COMMENT 'Foreign Key that related to the work_status table.',
  `work_j_id` INT UNSIGNED NULL COMMENT 'Foreign Key to J phase.',
  `work_c_id` INT UNSIGNED NULL COMMENT 'Foreign key to C phase.',
  `work_p_id` INT UNSIGNED NULL COMMENT 'Foreign key to P phase.',
  `work_b_id` INT UNSIGNED NULL COMMENT 'Foreign key to B phase.',
  `work_s_id` INT UNSIGNED NULL COMMENT 'Foreign key to S phase.',
  `work_created` DATETIME NULL COMMENT 'Historical reference as to when the entry was created.',
  `work_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change to the entry was created.',
  PRIMARY KEY (`work_id`),
  INDEX `fk_work_status_idx` (`work_status` ASC),
  INDEX `fk_work_j_id_idx` (`work_j_id` ASC),
  INDEX `fk_work_c_id_idx` (`work_c_id` ASC),
  INDEX `fk_work_s_id_idx` (`work_s_id` ASC),
  INDEX `fk_work_p_id_idx` (`work_p_id` ASC),
  INDEX `fk_client_id_idx` (`work_client` ASC),
  INDEX `fk_work_b_id_idx` (`work_b_id` ASC),
  CONSTRAINT `fk_work_status`
    FOREIGN KEY (`work_status`)
    REFERENCES `OPSDev`.`work_status` (`work_status_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_j_id`
    FOREIGN KEY (`work_j_id`)
    REFERENCES `OPSDev`.`work_j` (`work_j_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_c_id`
    FOREIGN KEY (`work_c_id`)
    REFERENCES `OPSDev`.`work_c` (`work_c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_s_id`
    FOREIGN KEY (`work_s_id`)
    REFERENCES `OPSDev`.`work_s` (`work_s_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_p_id`
    FOREIGN KEY (`work_p_id`)
    REFERENCES `OPSDev`.`work_p` (`work_p_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_id`
    FOREIGN KEY (`work_client`)
    REFERENCES `OPSDev`.`addr` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_b_id`
    FOREIGN KEY (`work_b_id`)
    REFERENCES `OPSDev`.`work_b` (`work_b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_client_id`
    FOREIGN KEY (`work_client`)
    REFERENCES `OPSDev`.`addr_orgs` (`addr_orgs_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work - The master table for all work/projects.  All child tables underneath this table will begin with the previd work_.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
