-- MySQL Script generated by MySQL Workbench
-- 06/05/18 11:00:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`common_rfisub_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`common_rfisub_responses` (
  `common_rfisubs_responses_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `common_rfisubs_responses_type` INT(1) NULL,
  `common_rfisubs_responses_value` VARCHAR(100) NULL,
  PRIMARY KEY (`common_rfisubs_responses_id`))
ENGINE = InnoDB
COMMENT = 'common_rfisubs_responses - A lookup table containing the most typical RFI/Submittal responses.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_rfisub_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_rfisub_log` (
  `work_j_rfisub_log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for milestone enrty for a J phase SUB/RFI entry.',
  `work_j_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key.  References value \'work_j_id\' on parent table \'work_j\'.',
  `work_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Refernces to \'work_id\' of parent table \'work\'.',
  `work_j_rfisub_log_type` INT(1) NOT NULL COMMENT 'Defines if an entry is a submittal (0) or and rfi (1).',
  `work_j_rfisub_log_status` INT(1) NOT NULL DEFAULT 1 COMMENT 'Defines the status of an entry.  Values available...',
  `work_j_rfisub_log_internal_track` INT(5) NULL COMMENT 'Defines CDE\'s internal tracking number.',
  `work_j_rfisub_log_external_track` VARCHAR(45) NULL COMMENT 'Defines the external source tracking number.',
  `work_j_rfisub_log_receivedby` INT UNSIGNED NOT NULL COMMENT 'Foreign Key.  Identifies who recieved the document from the \'employee\' table.',
  `work_j_rfisub_log_date_received` DATE NULL COMMENT 'Defines the date recieved.',
  `work_j_rfisub_log_qty_received` INT NULL COMMENT 'Defines the quantity recieved.',
  `work_j_rfisub_log_due_date` DATE NULL COMMENT 'Defines the due date.',
  `work_j_rfisub_log_subject` VARCHAR(255) NULL COMMENT 'Defines the subject of the SUB/RFI.',
  `work_j_rfisub_log_disposition` INT UNSIGNED NOT NULL COMMENT 'Defines the pre-defined disposition.',
  `work_j_rfisub_log_notes` TEXT NULL COMMENT 'Defines any notes related to the SUBS/RFI.',
  `work_j_rfisub_log_date_returned` DATE NULL COMMENT 'Defines the date the documents were actually returned.',
  `work_j_rfisub_log_qty_returned` INT(3) NULL COMMENT 'Defines the quantity that was returned.',
  `work_j_rfisub_log_created` DATETIME NULL COMMENT 'Historical reference as to when the entry was created.',
  `work_j_rfisub_log_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change to the record was performed.',
  PRIMARY KEY (`work_j_rfisub_log_id`),
  INDEX `fk_work_j_rfisub_log_common_rfisub_responses_work_j_rfisu_idx` (`work_j_rfisub_log_disposition` ASC),
  INDEX `fk_work_j_rfisub_log_work_j_work_j_id_idx` (`work_j_id` ASC),
  INDEX `fk_work_j_rfisub_log_employee_work_j_rfisub_recievedby_idx` (`work_j_rfisub_log_receivedby` ASC),
  CONSTRAINT `fk_j_rfisub-responses`
    FOREIGN KEY (`work_j_rfisub_log_disposition`)
    REFERENCES `OPSDev`.`common_rfisub_responses` (`common_rfisubs_responses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_j_rfisubs-work_j_id`
    FOREIGN KEY (`work_j_id`)
    REFERENCES `OPSDev`.`work_j` (`work_j_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_j_rfisubs-recievedby`
    FOREIGN KEY (`work_j_rfisub_log_receivedby`)
    REFERENCES `OPSDev`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work_j_rfisub_log - A Child table that holds all RFI/Submittal infromation for a J phase Work assignment.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_rfisub_log_reviewers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_rfisub_log_reviewers` (
  `work_j_rfisub_log_reviewers_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `work_j_rfisub_log_id` INT UNSIGNED NOT NULL,
  `work_j_rfisub_log_reviewers_employee` INT UNSIGNED NULL,
  `work_j_rfisub_log_reviewers_consultants` INT UNSIGNED NULL,
  PRIMARY KEY (`work_j_rfisub_log_reviewers_id`),
  INDEX `fk_work_j_rfisub_log_reviewers_work_j_consulants_addr_work_idx` (`work_j_rfisub_log_reviewers_consultants` ASC),
  INDEX `fk_work_j_rfisub_log_reviewrs_employee_work_j_rfisub_log__idx` (`work_j_rfisub_log_reviewers_employee` ASC),
  INDEX `fk_work_j_rfisub_log_reviewers_workj_rfisub_log_work_j_lo_idx` (`work_j_rfisub_log_id` ASC),
  CONSTRAINT `fk_j_rfisubs-consultants`
    FOREIGN KEY (`work_j_rfisub_log_reviewers_consultants`)
    REFERENCES `OPSDev`.`addr` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_j_rfisubs-employee`
    FOREIGN KEY (`work_j_rfisub_log_reviewers_employee`)
    REFERENCES `OPSDev`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_j_rfisubs-log_id`
    FOREIGN KEY (`work_j_rfisub_log_id`)
    REFERENCES `OPSDev`.`work_j_rfisub_log` (`work_j_rfisub_log_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work_j_rfisubs_log_reviewers - A child table that holds all related reviewers of RFI/Submittal entries.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
