-- MySQL Script generated by MySQL Workbench
-- 02/07/18 14:38:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work` (
  `work_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  A unique identifier for work entries.',
  `work_year` YEAR NULL COMMENT 'Defines the archive year of the project in YEAR only format',
  `work_number` VARCHAR(10) NOT NULL COMMENT 'Defines the job number suffix.  Format is YY-XXX',
  `work_title` TEXT NOT NULL COMMENT 'Defines the title of the job.',
  `work_client` INT UNSIGNED NOT NULL COMMENT 'Foreign key to the ADDR_ORGS table.',
  `work_client_rep` INT UNSIGNED NOT NULL COMMENT 'The name from the ADDR entry',
  `work_db` TINYINT(1) NULL COMMENT 'Defines if a project is a Design/Build project',
  `work_status` INT UNSIGNED NULL COMMENT 'Foreign Key that related to the work_status table.',
  `work_j_id` INT UNSIGNED NULL COMMENT 'Foreign Key to J phase.',
  `work_c_id` INT UNSIGNED NULL COMMENT 'Foreign key to C phase.',
  `work_p_id` INT UNSIGNED NULL COMMENT 'Foreign key to P phase.',
  `work_b_id` INT UNSIGNED NULL COMMENT 'Foreign key to B phase.',
  `work_s_id` INT UNSIGNED NULL COMMENT 'Foreign key to S phase.',
  `work_created` DATETIME NULL COMMENT 'Historical reference as to when the entry was created.',
  `work_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change to the entry was created.',
  PRIMARY KEY (`work_id`),
  INDEX `fk_work_status_idx` (`work_status` ASC),
  INDEX `fk_work_j_id_idx` (`work_j_id` ASC),
  INDEX `fk_work_c_id_idx` (`work_c_id` ASC),
  INDEX `fk_work_s_id_idx` (`work_s_id` ASC),
  INDEX `fk_work_p_id_idx` (`work_p_id` ASC),
  INDEX `fk_work_b_id_idx` (`work_b_id` ASC),
  INDEX `fk_work_client_id_idx` (`work_client_rep` ASC),
  INDEX `fk_client_id_idx` (`work_client` ASC),
  CONSTRAINT `fk_work_status`
    FOREIGN KEY (`work_status`)
    REFERENCES `OPSDev`.`work_status` (`work_status_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_j_id`
    FOREIGN KEY (`work_j_id`)
    REFERENCES `OPSDev`.`work_j` (`work_j_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_c_id`
    FOREIGN KEY (`work_c_id`)
    REFERENCES `OPSDev`.`work_c` (`work_c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_s_id`
    FOREIGN KEY (`work_s_id`)
    REFERENCES `OPSDev`.`work_s` (`work_s_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_p_id`
    FOREIGN KEY (`work_p_id`)
    REFERENCES `OPSDev`.`work_p` (`work_p_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_id`
    FOREIGN KEY (`work_client`)
    REFERENCES `OPSDev`.`addr_orgs` (`addr_orgs_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_b_id`
    FOREIGN KEY (`work_b_id`)
    REFERENCES `OPSDev`.`work_b` (`work_b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_client_id`
    FOREIGN KEY (`work_client_rep`)
    REFERENCES `OPSDev`.`addr` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work - The master table for all work/projects.  All child tables underneath this table will begin with the previd work_.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
