-- MySQL Script generated by MySQL Workbench
-- 11/14/18 09:19:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_consultants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_consultants` (
  `work_j_consultants_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for a individual memebers of a the external team. ',
  `work_j_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. References value \'work_j_id\' on parent table \'work_j\'.',
  `work_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Refernces to \'work_id\' of parent table \'work\'. ',
  `addr_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Refernces to \'addr_id\' from the addr table.',
  `common_roles_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Refernces to \'common_roles_id\' of parent table \'common_roles\'. ',
  `work_j_consultants_created` DATETIME NULL,
  `work_j_consultants_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_j_consultants_id`),
  INDEX `fk_addr_id_idx` (`addr_id` ASC),
  INDEX `fk_work_j_id_idx` (`work_j_id` ASC),
  INDEX `fk_j_consultants-common_roles_id_idx` (`common_roles_id` ASC),
  CONSTRAINT `fk_j_consultants-addr_id`
    FOREIGN KEY (`addr_id`)
    REFERENCES `OPSDev`.`addr` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_j_consultants-work_j_id`
    FOREIGN KEY (`work_j_id`)
    REFERENCES `OPSDev`.`work_j` (`work_j_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_j_consultants-common_roles_id`
    FOREIGN KEY (`common_roles_id`)
    REFERENCES `OPSDev`.`common_roles` (`common_roles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'work_j_consultants - A child table that holds all related consultants that may be working on a J phase Work assignment.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
