-- MySQL Script generated by MySQL Workbench
-- 11/08/17 11:12:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`work_j`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j` (
  `work_j_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for a J phase work project.',
  `work_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Refernces to \'work_id\' of parent table \'work\'.',
  `work_status_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Defines the status of the J phase.  Refers to values held in table \'work_status\'.',
  `work_j_percentcomp` DECIMAL(10,2) NULL COMMENT 'Defines the percentage of completion for a J phase project.',
  `work_j_sow` TEXT NULL COMMENT 'Defines the statement of work for a J phase project.',
  `work_j_created` DATETIME NULL COMMENT 'Historical reference as to when the entry was created.',
  `work_j_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change to the S phase entry was created.',
  PRIMARY KEY (`work_j_id`),
  INDEX `fk_work_status_id_idx` (`work_status_id` ASC),
  CONSTRAINT `fk_work_j-status_id`
    FOREIGN KEY (`work_status_id`)
    REFERENCES `OPSDev`.`work_status` (`work_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'work_j - A child table that contains all relevant project information related J phase projects.  All child tables underneath this table will be begin with work_j_.\n\n';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_c`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_c` (
  `work_c_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `work_id` INT UNSIGNED NOT NULL,
  `work_status_id` INT UNSIGNED NOT NULL,
  `work_c_percentcomp` DECIMAL(10,2) NULL,
  `work_c_sow` TEXT NULL,
  `work_c_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_c_id`),
  INDEX `fk_work_c_status_id_idx` (`work_status_id` ASC),
  CONSTRAINT `fk_c_work-status_id`
    FOREIGN KEY (`work_status_id`)
    REFERENCES `OPSDev`.`work_status` (`work_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'work_c - A child table that contains all relevant project informatino related to C phase projects.  All child tables underneath this table will begin with work_c_.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_s` (
  `work_s_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for a S phase work project.',
  `work_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Refernces to \'work_id\' of parent table \'work\'.',
  `work_status_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Defines the status of the S phase.  Refers to values held in table \'work_status\'.',
  `work_s_percentcomp` DECIMAL(10,2) NULL COMMENT 'Defines a percentage of completion for the S phase.',
  `work_s_sow` TEXT NULL COMMENT 'Statement of work definition in text',
  `work_s_created` DATETIME NULL COMMENT 'Historical reference as to when a change to the S phase entry was created.',
  `work_s_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change to the entry was created.',
  PRIMARY KEY (`work_s_id`),
  INDEX `fk_work_s-work_status_id_idx` (`work_status_id` ASC),
  CONSTRAINT `fk_work_s-work_status_id`
    FOREIGN KEY (`work_status_id`)
    REFERENCES `OPSDev`.`work_status` (`work_status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work_s - A child table that contains all relevant project informatino related to S phase projects.  All child tables underneath this table will begin with work_s_.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_p`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_p` (
  `work_p_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `work_id` INT UNSIGNED NOT NULL,
  `work_status_id` INT UNSIGNED NOT NULL,
  `work_p_fcv` DECIMAL(10,2) NULL DEFAULT 0.00,
  `work_p_percentcompl` DECIMAL(10,2) NULL,
  `work_p_sow` TEXT NULL,
  `work_p_created` DATETIME NULL,
  `work_p_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_p_id`),
  INDEX `fk_work_p-status_id_idx` (`work_status_id` ASC),
  CONSTRAINT `fk_work_p-status_id`
    FOREIGN KEY (`work_status_id`)
    REFERENCES `OPSDev`.`work_status` (`work_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'work_p - A child table that contains all relevant project information related P phase projects.  All child tables underneath this table will be begin with work_p_.\n';


-- -----------------------------------------------------
-- Table `OPSDev`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work` (
  `work_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  A unique identifier for work entries.',
  `work_year` YEAR NULL COMMENT 'Defines the archive year of the project in YEAR only format',
  `work_number` VARCHAR(10) NOT NULL COMMENT 'Defines the job number suffix.  Format is YY-XXX',
  `work_title` TEXT NOT NULL COMMENT 'Defines the title of the job.',
  `work_client` INT UNSIGNED NOT NULL COMMENT 'Foreign key',
  `work_client_rep` VARCHAR(150) NOT NULL,
  `work_db` TINYINT(1) NULL,
  `work_status` INT(1) UNSIGNED NOT NULL,
  `work_j_id` INT UNSIGNED NULL,
  `work_c_id` INT UNSIGNED NULL,
  `work_p_id` INT UNSIGNED NULL,
  `work_b_id` INT UNSIGNED NULL,
  `work_s_id` INT UNSIGNED NULL,
  `work_created` DATETIME NULL,
  `work_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_id`),
  INDEX `fk_work_status_idx` (`work_status` ASC),
  INDEX `fk_work_j_id_idx` (`work_j_id` ASC),
  INDEX `fk_work_c_id_idx` (`work_c_id` ASC),
  INDEX `fk_work_s_id_idx` (`work_s_id` ASC),
  INDEX `fk_work_p_id_idx` (`work_p_id` ASC),
  INDEX `fk_client_id_idx` (`work_client` ASC),
  CONSTRAINT `fk_work_status`
    FOREIGN KEY (`work_status`)
    REFERENCES `OPSDev`.`work_status` (`work_status_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_j_id`
    FOREIGN KEY (`work_j_id`)
    REFERENCES `OPSDev`.`work_j` (`work_j_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_c_id`
    FOREIGN KEY (`work_c_id`)
    REFERENCES `OPSDev`.`work_c` (`work_c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_s_id`
    FOREIGN KEY (`work_s_id`)
    REFERENCES `OPSDev`.`work_s` (`work_s_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_work_p_id`
    FOREIGN KEY (`work_p_id`)
    REFERENCES `OPSDev`.`work_p` (`work_p_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_id`
    FOREIGN KEY (`work_client`)
    REFERENCES `OPSDev`.`addr` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work - The master table for all work/projects.  All child tables underneath this table will begin with the previd work_.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
