-- MySQL Script generated by MySQL Workbench
-- 08/02/18 10:10:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`common_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`common_roles` (
  `common_roles_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identified for a common role.',
  `common_roles_desc` VARCHAR(255) NULL COMMENT 'Defines the label of a common role.',
  PRIMARY KEY (`common_roles_id`))
ENGINE = InnoDB
COMMENT = 'common_roles - A lookup table containing the most common job roles held within the company for any type of work.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_manhours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_manhours` (
  `work_j_manhours_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for a manhour entry.',
  `work_j_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key.  References value \'work_j_id\' on parent table \'work_j\'.',
  `work_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key. Refernces to \'work_id\' of parent table \'work\'.',
  `common_roles_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key.  Defines the labeling for a manhour entry.  References \'common_roles_id\' on the table \'common_roles\'.',
  `work_j_manhours_est` INT NULL COMMENT 'Defines the estimated hours set aside for a project.',
  `work_j_manhours_act` INT NULL COMMENT 'Defines the acutal number of hours spent on a project.',
  `work_j_manhours_created` DATETIME NULL COMMENT 'Historical reference as to when the entry was created.',
  `work_j_manhours_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when the entry was updated.',
  PRIMARY KEY (`work_j_manhours_id`),
  INDEX `fk_work_j_id_idx` (`work_j_id` ASC),
  INDEX `fk_common_roles_id_idx` (`common_roles_id` ASC),
  CONSTRAINT `fk_j_manhours-work_j_id`
    FOREIGN KEY (`work_j_id`)
    REFERENCES `OPSDev`.`work_j` (`work_j_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_j_manhours-roles_id`
    FOREIGN KEY (`common_roles_id`)
    REFERENCES `OPSDev`.`common_roles` (`common_roles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'work_j_manhours - A child table that holds all programmed manhour information related to a J Phase Work assignment.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
