-- MySQL Script generated by MySQL Workbench
-- 06/08/18 11:50:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OPSDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OPSDev` DEFAULT CHARACTER SET utf8 ;
USE `OPSDev` ;

-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_acct_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_acct_info` (
  `work_j_acct_info_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `work_j_id` INT UNSIGNED NOT NULL,
  `work_id` INT UNSIGNED NOT NULL,
  `work_j_acct_info_istm` TINYINT(1) NULL,
  `work_j_acct_info_contract_value` DECIMAL(15,2) NULL,
  `work_j_acct_info_created` DATETIME NULL,
  `work_j_acct_info_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_j_acct_info_id`),
  INDEX `fk_work_j_id_idx` (`work_j_id` ASC),
  CONSTRAINT `fk_j_acctinfo-work_j_id`
    FOREIGN KEY (`work_j_id`)
    REFERENCES `OPSDev`.`work_j` (`work_j_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work_j_acct_info - A child table that holds all relevant accounting information for a J phase Work assignment.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_acct_inv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_acct_inv` (
  `work_j_acct_inv_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `work_j_acct_info_id` INT UNSIGNED NOT NULL,
  `work_j_acct_inv_amount` DECIMAL(10,2) NULL,
  `work_j_acct_inv_date` DATE NULL,
  `work_j_acct_inv_ispaid` TINYINT(1) NULL,
  `work_j_acct_inv_created` DATETIME NULL,
  `work_j_acct_inv_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`work_j_acct_inv_id`),
  INDEX `fj_j_acct_inv-acct_info_id_idx` (`work_j_acct_info_id` ASC),
  CONSTRAINT `fj_j_acct_inv-acct_info_id`
    FOREIGN KEY (`work_j_acct_info_id`)
    REFERENCES `OPSDev`.`work_j_acct_info` (`work_j_acct_info_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'work_j_acct_inv - A child table that holds the records of invoices applied to the J phase project.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_acct_subs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_acct_subs` (
  `work_j_acct_subs_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key.  Unique identifier for a subs that are contracted.',
  `work_j_acct_info_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key.  Refers to the \'work_j_acct_id\' column of the work_j_acct_info table.',
  `addr_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key.  Refers to the \'addr_id\' column of the addr idea',
  `work_j_acct_subs_ca` DECIMAL(10,2) NULL COMMENT 'Contract amount agreed to by sub',
  `work_j_acct_subs_created` DATETIME NULL COMMENT 'Historical reference as to when a record was created.',
  `work_j_acct_subs_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Historical reference as to when a change has been made to the record.',
  PRIMARY KEY (`work_j_acct_subs_id`),
  INDEX `fj_j_acct_subs-acct_info_id_idx` (`work_j_acct_info_id` ASC),
  INDEX `fk_j_acct_subs-addr_idx` (`addr_id` ASC),
  CONSTRAINT `fk_j_acct_subs-acct_info_id`
    FOREIGN KEY (`work_j_acct_info_id`)
    REFERENCES `OPSDev`.`work_j_acct_info` (`work_j_acct_info_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_j_acct_subs-addr`
    FOREIGN KEY (`addr_id`)
    REFERENCES `OPSDev`.`addr` (`addr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'work_j_acc - A child tbale that holds all related work account information for subs.';


-- -----------------------------------------------------
-- Table `OPSDev`.`work_j_acct_subs_inv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OPSDev`.`work_j_acct_subs_inv` (
  `work_j_acct_subs_inv_id` INT UNSIGNED NOT NULL COMMENT 'Primary Key.  Unique identifier for a subs that are contracted.',
  `work_j_acct_subs_id` INT UNSIGNED NOT NULL COMMENT 'Foreign Key.  Refers to the \'work_j_acct_subs_id\' column in the work_j_acct_subs table.',
  `work_j_acct_subs_inv_number` VARCHAR(45) NOT NULL COMMENT 'The invoice number from sub.',
  `work_j_acct_subs_inv_amount` DECIMAL(10,2) NULL COMMENT 'Amount of the invoice.',
  `work_j_acct_subs_inv_date` DATE NULL COMMENT 'Date invoice was received.',
  `work_j_acct_subs_inv_ispaid` TINYINT(1) NULL COMMENT 'Flag to mark if invoice has been paid or not.',
  `work_j_acct_subs_inv_date_paid` DATE NULL COMMENT 'Date invocie was paid by CDE.',
  `work_j_acct_subs_inv_created` DATETIME NULL COMMENT 'Historical reference as to when a record was created.',
  `work_j_acct_subs_inv_updated` TIMESTAMP NULL COMMENT 'Historical reference as to when a record was updated.',
  PRIMARY KEY (`work_j_acct_subs_inv_id`),
  INDEX `fk_subs_inv-acct_subs_idx` (`work_j_acct_subs_id` ASC),
  CONSTRAINT `fk_subs_inv-acct_subs_id`
    FOREIGN KEY (`work_j_acct_subs_id`)
    REFERENCES `OPSDev`.`work_j_acct_subs` (`work_j_acct_subs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
